# Generated by Django 4.2 on 2023-04-24 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_user_id_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='usuario',
        ),
        migrations.CreateModel(
            name='RealizaTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default='2023-04-24')),
                ('idTransaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.transaccion')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='realizatransaccion',
            constraint=models.UniqueConstraint(fields=('idUsuario', 'idTransaccion'), name='unique_realizatransaccion'),
        ),
    ]
